version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./logs:/app/logs

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    depends_on:
      - app
    volumes:
      - ./client:/app
volumes:
  db_data: